// Generated by scripts/generate-action-keymap.ts. Do not edit.
// Source: src/renderer/src/features/actions/model/{app,session}.ts
#[rustfmt::skip]
pub(super) const COMMANDS: &[(&str, &str, &str)] = &[
    (r#"session.new"#, r#"New Session"#, r#"super+t"#),
    (r#"session.close"#, r#"Close Session"#, r#"super+w"#),
    (r#"session.next"#, r#"Next Session"#, r#"ctrl+tab"#),
    (r#"session.previous"#, r#"Previous Session"#, r#"ctrl+shift+tab"#),
    (r#"app.palette.open"#, r#"Command Palette"#, r#"super+shift+p"#),
];
