import { readFile, writeFile, mkdir } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname } from "node:path";
import { keymapDefaults } from "../src/renderer/src/features/actions/model/registry.ts";

// Rust raw literals preserve Unicode, quotes and backslashes without JS/Rust
// escape differences. Choose a delimiter that cannot occur in the declaration.
function rustString(value: string): string {
  let hashes = "#";
  while (value.includes(`"${hashes}`)) hashes += "#";
  return `r${hashes}"${value}"${hashes}`;
}
const output = fileURLToPath(
  new URL("../src/backend/src/keymap/action_definitions.rs", import.meta.url),
);
const content = [
  "// Generated by scripts/generate-action-keymap.ts. Do not edit.",
  "// Source: src/renderer/src/features/actions/model/{app,session}.ts",
  "#[rustfmt::skip]",
  "pub(super) const COMMANDS: &[(&str, &str, &str)] = &[",
  ...keymapDefaults.map(
    (entry) => `    (${entry.map(rustString).join(", ")}),`,
  ),
  "];",
  "",
].join("\n");
const args = process.argv.slice(2);
if (args.some((arg) => arg !== "--check"))
  throw new Error("Usage: node scripts/generate-action-keymap.ts [--check]");
if (args.includes("--check")) {
  const existing = await readFile(output, "utf8").catch(
    (error: NodeJS.ErrnoException) => {
      if (error.code === "ENOENT") return "";
      throw error;
    },
  );
  if (existing !== content)
    throw new Error(
      "Action keymap metadata is stale. Run npm run actions:generate and commit the result.",
    );
  console.log("Action keymap metadata is in sync.");
} else {
  await mkdir(dirname(output), { recursive: true });
  await writeFile(output, content);
  console.log(`Generated ${output}`);
}
